// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egfgybojsbpikdthuifb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZmd5Ym9qc2JwaWtkdGh1aWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODgwMjAsImV4cCI6MjA3MTY2NDAyMH0.Lxqilc71gkL1szQtFx_OgiXvQ_-Ob7PxMSOLvphhq8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});